# Generated by Django 3.0.5 on 2020-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200427_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='contact1tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact2tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
