# Generated by Django 3.0.5 on 2020-05-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200504_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='branch',
            field=models.CharField(blank=True, default='n/a', max_length=255, null=True),
        ),
    ]
