# Generated by Django 3.0.5 on 2020-04-29 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatefirstname', models.CharField(max_length=255)),
                ('candidatemiddlenames', models.CharField(blank=True, max_length=255, null=True)),
                ('candidatefamilyname', models.CharField(max_length=255)),
                ('candidatesalutation', models.CharField(blank=True, max_length=255, null=True)),
                ('candidateemail', models.CharField(blank=True, max_length=255, null=True)),
                ('referencestatus', models.IntegerField(db_column='ReferenceStatus', default=3)),
                ('referencerequested', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencereceived', models.DateTimeField(db_column='ReferenceReceived', default=django.utils.timezone.now)),
                ('passportstatus', models.IntegerField(db_column='PassportStatus', default=3)),
                ('passportchecked', models.DateTimeField(db_column='PassportChecked', default=django.utils.timezone.now)),
                ('ccjstatus', models.IntegerField(db_column='CCJ', default=3)),
                ('ccjchecked', models.DateTimeField(db_column='ccjChecked', default=django.utils.timezone.now)),
                ('righttoworkstatus', models.IntegerField(db_column='RightToWork', default=3)),
                ('righttoworkchecked', models.DateTimeField(db_column='RightToWorkChecked', default=django.utils.timezone.now)),
                ('enhanceddbsstatus', models.IntegerField(db_column='EnhancedDBS', default=3)),
                ('enhanceddbschecked', models.DateTimeField(db_column='EnhanceddbsChecked', default=django.utils.timezone.now)),
                ('dbsstatus', models.IntegerField(db_column='DBS', default=3)),
                ('dbschecked', models.DateTimeField(db_column='dbsChecked', default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate',
                'managed': True,
            },
        ),
    ]
