# Generated by Django 3.0.5 on 2020-05-04 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20200429_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='dob',
            field=models.DateTimeField(db_column='dob', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dvlc',
            field=models.IntegerField(db_column='dvlc', default=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dvlcpoints',
            field=models.IntegerField(db_column='dvlcpoints', default=1),
        ),
    ]
